Seller Model
Gomerce/GomerceBE pull request #35
Opened 2022-09-22 08:45 UTC by LoveHope5

Here is the seller model file

2022-09-26 22:45 UTC, Ajioz reviewed
Hi there,

Nice work going around.

I am sure you intend to make a PR to your session lead repo.

According to the workflow, the team lead would make a PR from his repo to the Gomerce repo where we'll review all the work your team has done. 

**Please note:**
Your team lead would be willing to review your PR against his/her repo and merge on that level.  Meaning he shall do this for every member of his team, and make a single PR to the Gomerce repo, which is a sum of your teamwork.

2022-10-04 12:40 UTC, samdoghor commented on src/models/seller.py
> +    """ The Customer model """
Seller not Customer

2022-10-04 13:05 UTC, samdoghor commented on src/models/seller.py
> +    store_id = db.Column(db.Integer)
Store_id is a foreign key, you did indicate it in your file

2022-10-04 13:08 UTC, samdoghor requested changes
- Make your PR to samdoghor/GomerceB repo not the central repo.
- the following columns are missing: phone_verified and rating

2022-10-04 13:09 UTC, samdoghor commented
Also, please git pull before making your new changes and resolve every conflicts

2022-10-04 13:09 UTC, closed without merging